// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nadina_Proiect3.Data;

#nullable disable

namespace Nadina_Proiect3.Migrations
{
    [DbContext(typeof(Nadina_Proiect3Context))]
    [Migration("20220107152853_baie")]
    partial class baie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Nadina_Proiect3.Models.Baie", b =>
                {
                    b.Property<int>("BaieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaieId"), 1L, 1);

                    b.Property<int>("Cod")
                        .HasColumnType("int");

                    b.Property<string>("Culoare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BaieId");

                    b.ToTable("Baie");
                });

            modelBuilder.Entity("Nadina_Proiect3.Models.Categorie", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategorieId"), 1L, 1);

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieId");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Nadina_Proiect3.Models.CategorieProdus", b =>
                {
                    b.Property<int>("CategorieProdusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategorieProdusId"), 1L, 1);

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<int>("ProdusId")
                        .HasColumnType("int");

                    b.HasKey("CategorieProdusId");

                    b.HasIndex("CategorieId");

                    b.HasIndex("ProdusId");

                    b.ToTable("CategorieProdus");
                });

            modelBuilder.Entity("Nadina_Proiect3.Models.Dormitor", b =>
                {
                    b.Property<int>("DormitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DormitorId"), 1L, 1);

                    b.Property<int>("Cod")
                        .HasColumnType("int");

                    b.Property<string>("Culoare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DormitorId");

                    b.ToTable("Dormitor");
                });

            modelBuilder.Entity("Nadina_Proiect3.Models.Living", b =>
                {
                    b.Property<int>("LivingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LivingId"), 1L, 1);

                    b.Property<int>("Cod")
                        .HasColumnType("int");

                    b.Property<string>("Culoare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LivingId");

                    b.ToTable("Living");
                });

            modelBuilder.Entity("Nadina_Proiect3.Models.Produs", b =>
                {
                    b.Property<int>("ProdusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdusId"), 1L, 1);

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<int>("Cod")
                        .HasColumnType("int");

                    b.Property<string>("Culoare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProdusId");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("Nadina_Proiect3.Models.CategorieProdus", b =>
                {
                    b.HasOne("Nadina_Proiect3.Models.Categorie", "Categorie")
                        .WithMany("CategoriiProdus")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nadina_Proiect3.Models.Produs", "Produs")
                        .WithMany("CategoriiProdus")
                        .HasForeignKey("ProdusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("Nadina_Proiect3.Models.Categorie", b =>
                {
                    b.Navigation("CategoriiProdus");
                });

            modelBuilder.Entity("Nadina_Proiect3.Models.Produs", b =>
                {
                    b.Navigation("CategoriiProdus");
                });
#pragma warning restore 612, 618
        }
    }
}
